### ISSUE TITLE
Dependency graph for formulas

### ISSUE THREAD

**Issue by mercurial-moon** [karlb/litespread#2]
Does `litespread` calculate dependencies for formula columns like spreadsheet software would do.
eg.

if A, B, C, D are columns
A = B + C
B = D - C
if B changes will A be recalculated?

Also are cross table formula's supported?

**Comment by karlb** [comment]
Dependencies within a table should be properly resolved as long as they are not circular. The code for that is https://github.com/karlb/litespread/blob/master/src/backend/litespread.js#L34-L79

> Also are cross table formula's supported?

Referencing another table from a formula column in a table is not supported., but you can create a view that selects from multiple tables.
